name: Restless Souls
favicon: null
layout_spectrum: 0
typography_spectrum: 0.06825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000200'
    - '#ffffff'
    - '#ea2900'
    - '#68b800'
    - '#436d01'
  brandStrength: 0.2585955017711967
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
